import { Inter } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TravelHub | Top level Services Let's Travel with us",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modals }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {modals}
        {children}
        <Footer />
      </body>
    </html>
  );
}
